### ISSUE TITLE
Can't get wlogout right

### ISSUE THREAD

**Issue by Muizzyranking** [iamhrigved/Hyprdots#2]
How can i make my wlogout like yours? I can't seem to get it to look like yours.

**Comment by iamhrigved** [comment]
Can you please provide a more detailed explanation of what's not working?

I think you can't get all the buttons to the same line right? If so, you have to change the command which you are using to open wlogout.

It should be `wlogout --buttons-per-row 6` or in short, `wlogout -b 6`. You can see this in my `.config/hypr/scripts/power-menu.sh` file.

**Comment by iamhrigved** [comment]
No response. Closed.
